// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	FindBySymbol(ctx context.Context, symbol string) ([]FindBySymbolRow, error)
	GetCurrency(ctx context.Context, name string) (Currency, error)
	ListCurrencies(ctx context.Context, arg ListCurrenciesParams) ([]Currency, error)
	RegisterOHLC(ctx context.Context, arg RegisterOHLCParams) (Ohlc, error)
	ResisterCurrency(ctx context.Context, arg ResisterCurrencyParams) (Currency, error)
}

var _ Querier = (*Queries)(nil)
